// requirements: webpack ,  webpack-cli

const webpack = require('webpack')
const path = require('path')

module.exports = {

    // debugging 
    devtool:'inline-source-map',
    entry: {
        index: './src/index.js'
    },

    output: {
        // path.resolve :
        // path.join :
        path: path.resolve(__dirname, 'dist'),  
        filename: 'main.js'
    },

    //we can use different rules by adding different object.
    module: {
        rules: [
            {
                // babel use garera  es5, es6, es7, browser compatable.
                // use babel on which files
                // \ is used to escape a character.
                test: /\.js$/,
                exclude: /node_modules/,
                use: 'babel-loader'
            }
        ]
    },

    devServer:{
        // those content that are not generated by webpack
        contentBase: path.join(__dirname, "public/"),
        port:3000,
        // to serve webpack files
        hot:true,
        publicPath: 'http://localhost:3000/dist/'
    }
}
